### ISSUE TITLE
Header Search Icon not Centered Properly

### ISSUE THREAD

**Issue by joshidipesh12** [joshidipesh12/travming-website#1]
The search icon uses <Image/> from nextjs with fixed layout and square dimensions. The Icon is Not Centered properly with respect to other content in the header.

![Issue Screenshot](https://user-images.githubusercontent.com/66198105/135741048-b46c7a3b-00bc-4146-86bc-a02d36f78f8f.png)

**Comment by kanadeakshay** [comment]
Hi,
I know how to do it and solved it also.
